---
- name: byod
  hosts: localhost
  connection: local

  vars_files:
    - ../vars/gpg.yml
    - ../vars/pass.yml
    - ../vars/synology.yml

  vars_prompt:
    - name: passphrase
      prompt: Type in your GPG passphrase
    - name: backup_user
      prompt: Choose Synology user
      private: false

  roles:
    - role: brainfartlab.overlord.credentials
      vars:
        authorizations:
          pass: true
          github: true
          gpg: true
        repo: "{{ pass_repo }}"
        gpg_email: "{{ gpg.email }}"
        gpg_public_key: "{{ gpg.public_key }}"
        gpg_signing_key: "{{ gpg.signing_key }}"
        gpg_ownertrust: "{{ gpg.ownertrust }}"
        gpg_passphrase: "{{ passphrase }}"
    - role: brainfartlab.overlord.terminal
    - role: brainfartlab.overlord.python
    - role: brainfartlab.overlord.node
    - role: brainfartlab.overlord.golang
    - role: brainfartlab.overlord.rust
    - role: brainfartlab.overlord.synology
      vars:
        synology_ip: "{{ synology.ip }}"
        synology_user: "{{ backup_user }}"
        not_container: true
